### ISSUE TITLE
Load pretrained VGG Model

### ISSUE THREAD

**Issue by ulmefors** [Brok-Bucholtz/ADL-Beta#2]
In `main.py` `load_vgg(sess, vgg_path)` the instruction is to _Load Pretrained VGG Model into TensorFlow_. Are these files supposed to be provided in the repo? They are ignored in `data/.gitignore` and are therefore not uploaded to GitHub.

EDIT: Found the URL in `helper.py`. However, when running `main.py`the VGG model is not downloaded. Instead there's a message from the tests `AssertionError: tf.saved_model.loader.load() not called`.

**Comment by ashishbedi** [comment]
Getting the same error!

**Comment by ulmefors** [comment]
Comment out the tests when you begin development. Uncomment when you have implemented the corresponding function. You can download the vgg model manually at the url in helpers file.

**Comment by ashishbedi** [comment]
That worked! Thanks

**Comment by ksakmann** [comment]
I wish I had come here 2h ago....
