### ISSUE TITLE
Load vgg - google.protobuf.message.DecodeError: Error parsing message

### ISSUE THREAD

**Issue by carlosgalvezp** [Brok-Bucholtz/ADL-Beta#4]
I have this code in load_vgg:

```
    graph_path = os.path.join(vgg_path, 'saved_model.pb')
    graph_def = tf.GraphDef()

    with open(graph_path, 'rb') as f:
        graph_def.ParseFromString(f.read())
```
However when I run the code I get this error:
```google.protobuf.message.DecodeError: Error parsing message```

I am using:
Python 3.5.2
Tensorflow 1.1.0 (pip)
Protobuf 3.3.0

**Comment by avidalh** [comment]
Hi Carlos,

I've used the following code:
```python
def load_vgg(sess, vgg_path):
    """
    Load Pretrained VGG Model into TensorFlow.
    :param sess: TensorFlow Session
    :param vgg_path: Path to vgg folder, containing "variables/" and "saved_model.pb"
    :return: Tuple of Tensors from VGG model (image_input, keep_prob, layer3_out, layer4_out, layer7_out)
    """
    # TODO: Implement function
   
    with tf.Session() as sess:
        tf.saved_model.loader.load(sess, ['vgg16'], vgg_path)
```

I've used TensorBoard to display the model: 
<img width="341" alt="screen shot 2017-06-15 at 08 24 03" src="https://user-images.githubusercontent.com/10057733/27169999-3817757a-51a4-11e7-91b8-d9528f564562.png">

Now I'm stuck on how to restore the model outputs... I have to read the tensorflow docu

**Comment by carlosgalvezp** [comment]
Hi Ángel,

What command did you use to visualize the graph in Tensorboard? I'm totally new to the new Tensorflow API so I pretty much need to start from scratch...

I'm trying:

tensorboard --logdir=<path_to_vgg_dir>

But it says it couldn't find any data

**Comment by avidalh** [comment]
Hi Carlos,
I've used the following:

- after loading the model yo have to create the summary for tensorboard:

<img width="737" alt="screen shot 2017-06-19 at 15 49 38" src="https://user-images.githubusercontent.com/10057733/27383021-0673ecd8-5681-11e7-86d6-186f782385b3.png">


the folder has to be created previously ;)

- and now you can load the model in tensorboard:
<img width="614" alt="screen shot 2017-06-19 at 15 38 49" src="https://user-images.githubusercontent.com/10057733/27383035-17d42d3a-5681-11e7-9383-084e2c362dcd.png">


And voila:

<img width="777" alt="screen shot 2017-06-19 at 15 50 49" src="https://user-images.githubusercontent.com/10057733/27383046-23633d94-5681-11e7-9835-d9213bf2d0c4.png">


Hope it helps :)
